## Put comments here that give an overall description of what your
## functions do

## The purpose of the pair of functions `makeCacheMatrix` and `cacheSolve` is to
## implement a caching solution for matrix inversion, which is generally a computationally
## costly process.
##
## A "special" matrix object is initially created with a call to 'makeCacheMatrix'.
## This object provides "public" get and set methods for reading or changing the stored
## matrix, and "private" methods to allow the `cacheSolve` function to read or initialize
## change the stored inverse --- it is not intended that the user call these "private"
## methods directly, though that is not expressly prevented.
##
## The `cacheSolve` function is used to obtain the inverse of the stored matrix; whether
## this is done by computation or by retrieval from the cache is abstracted from the user
## of `cacheSolve`.


## Write a short comment describing this function

## `makeCacheMatrix` takes as its parameter a matrix `x` (assumed to be invertible).
## It returns a list that references the following accessor and mutator functions:
##      x$set(y)                Sets (or resets) matrix 'x' to the supllied value.
##      x$get()                 Returns the stored matrix.
##      x$setInverse(inverse)   Sets (or resets) the inverse of 'x' to the supplied
##                              value.
##      x$getInverse()          Returns the currently stored inverse matrix.
makeCacheMatrix <- function(x = matrix()) {
        mat <- x
        inv <- NULL

        set <- function(y = NULL) {
                x <<- y      ## Assignment operator <<- ensures that
                             ## `x` refers to the variable defined in the parent
                             ## environment, and not to a local variable
                             ## in the `set` function environment.
                inv <<- NULL ## "Delete" any existing cached inverse
                             ## to ensure that it will be will be
                             ## recomputed at the next invocation of
                             ## `cacheSolve`.
                
        }
        
        ## The get function simply returns the stored matrix x.
        get <- function() x
        
        ## The setInverse function is used by the cacheSolve function to set
        ## the computed inverse matrix in the cache. Whether validly or
        ## otherwise it can also be used directly from the global environment
        ## or by a function other than cacheSolve to overwrite the stored inverse,
        ## in which case there would be no warning that a potentially incorrect
        ## inverse would be returned.
        
        setInverse <- function(inverse = NULL)
                inv <<- inverse
        
        getInverse <- function() inv
        
        ## Note: this list is returned.
        list(set = set, get = get,
             setInverse = setInverse,
             getInverse = getInverse)     
}


## Write a short comment describing this function

## 'cacheSolve' takes a list parameter `x` representing a "matrix cache"
## object generated by `makeCacheMatrix`. It either:
##      (a) computes the inverse of the matrix `x`, then stores it in
##          the cache; or
##      (b) returns the value of the inverse of `x` that is stored
##          in the cache.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        
        ## Determine whether a computed inverse exists in the cache.
        ## If so, return it.
        inv <- x$getInverse()         
        if(!is.null(inv)) {
                message("getting cached data")
                return(inv)
        }
        data <- x$get()
        
        ## Since no stored inverse is cached, compute the inverse,
        ## store it in the cache for future retrieval, then return it.
        ## Utilizes the `solve` function in the R base package.
        inv <- solve(data, ...)
        x$setInverse(inv)
        inv
}
